<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="5686" started-at="2019-01-16T12:13:18Z" finished-at="2019-01-16T12:13:23Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="5686" started-at="2019-01-16T12:13:18Z" finished-at="2019-01-16T12:13:23Z">
      <class name="com.clx.Test.LoginTest.LoginTest">
        <test-method status="PASS" signature="initialization(java.lang.String)[pri:0, instance:com.clx.Test.LoginTest.LoginTest@f5ac9e4]" name="initialization" is-config="true" duration-ms="5620" started-at="2019-01-16T12:13:18Z" finished-at="2019-01-16T12:13:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method status="FAIL" signature="TC_01(java.lang.String, java.lang.String)[pri:0, instance:com.clx.Test.LoginTest.LoginTest@f5ac9e4]" name="TC_01" duration-ms="0" started-at="2019-01-16T12:13:23Z" description=" Login with valid username and valid password" data-provider="Login" finished-at="2019-01-16T12:13:23Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Some DataProvider public java.lang.Object[][] com.clx.Test.LoginTest.LoginTest.LoginData(java.lang.String) throws java.io.IOException parameters unresolved:  at 0 type class java.lang.String
]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Some DataProvider public java.lang.Object[][] com.clx.Test.LoginTest.LoginTest.LoginData(java.lang.String) throws java.io.IOException parameters unresolved:  at 0 type class java.lang.String

at org.testng.internal.MethodInvocationHelper.getParameters(MethodInvocationHelper.java:197)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:130)
at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_01 -->
      </class> <!-- com.clx.Test.LoginTest.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
